# Generated by Django 5.2.6 on 2025-09-28 12:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_profile_reserved_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
